# Generated by Django 4.1.3 on 2023-09-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelfoodproducts',
            name='productCategory',
            field=models.CharField(blank=True, choices=[('Pizza', 'Pizza'), ('Other Food', 'Other Food')], default='Other Food', max_length=100, null=True, verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='hotelfoodproducts',
            name='product_second_name',
            field=models.CharField(blank=True, default='---', max_length=100, null=True, verbose_name='Product Second Name'),
        ),
    ]
