# Generated by Django 4.1.3 on 2023-09-07 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0003_hotelfoodorderitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDrinksCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0, verbose_name='Total Price')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Drinks Cart',
            },
        ),
        migrations.CreateModel(
            name='HotelDrinksOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteldrinkscart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Drinks Orders',
            },
        ),
        migrations.CreateModel(
            name='HotelDrinksProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Sayona', max_length=100, verbose_name='Product Name')),
                ('product_second_name', models.CharField(blank=True, default='Big', max_length=100, null=True, verbose_name='Product Second Name')),
                ('productCategory', models.CharField(blank=True, choices=[('Soft Drinks', 'Soft Drinks'), ('Beere', 'Beere')], default='Soft drinks', max_length=100, null=True, verbose_name='Product Category')),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('ProductQuantity', models.IntegerField(blank=True, null=True, verbose_name='Product Quantity')),
                ('InitialProductQuantity', models.IntegerField(blank=True, null=True, verbose_name='Initial Product Quantity')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/ProductsImages/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Drinks Products',
            },
        ),
        migrations.AddField(
            model_name='hotelfoodproducts',
            name='InitialProductQuantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Initial Product Quantity'),
        ),
        migrations.AlterField(
            model_name='hotelfoodproducts',
            name='product_second_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Product Second Name'),
        ),
        migrations.CreateModel(
            name='HotelDrinksOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteldrinksorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteldrinksproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Drinks Orders Items',
            },
        ),
        migrations.CreateModel(
            name='HotelDrinksCartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteldrinkscart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteldrinksproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Drinks Cart Items',
            },
        ),
    ]
