# Generated by Django 4.1.3 on 2023-09-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0004_hoteldrinkscart_hoteldrinksorder_hoteldrinksproducts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldrinksproducts',
            name='productCategory',
            field=models.CharField(blank=True, choices=[('Soft Drinks', 'Soft Drinks'), ('Beer', 'Beer')], default='Soft drinks', max_length=100, null=True, verbose_name='Product Category'),
        ),
    ]
