# Generated by Django 4.1.3 on 2023-09-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0007_hotelrooms_hotelroomscart_hotelroomsorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomscartitems',
            name='DaysNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Days'),
        ),
    ]
